# Generated by Django 4.0.2 on 2022-03-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_users_telephone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
